# Generated by Django 5.2.5 on 2026-02-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_account_branch_name_alter_account_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='account_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.account'),
        ),
        migrations.CreateModel(
            name='publish_ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('to_where', models.CharField(max_length=150)),
                ('from_where', models.CharField(max_length=150)),
                ('vehicle_rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
    ]
