# Generated by Django 5.2.5 on 2026-03-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vehicle_account_id_publish_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish_ride',
            old_name='vehicle_rider',
            new_name='rider_account',
        ),
    ]
